import turtle as t
from turtle import Screen
import math


def egldrawing():
    TL = float(input("Please enter the length of the line(TL):- "))
    TV = float(input("Please enter the top view of the line(TV):- "))
    FV = float(input("Please enter the front view of the line(FV):- "))
    d = float(input("Please enter the distance above the reference line:- "))
    e = float(input("Please enter the distance below the reference line:- "))

    angle1 = math.acos(TV / TL)
    angle1 = math.degrees(angle1)
    angle2 = math.acos(FV / TL)
    angle2 = math.degrees(angle2)

    t.left(90)
    t.forward(d * 10)
    t.right(90)
    t.forward(FV * 10)
    t.back(FV * 10)
    t.left(angle1)
    print(angle1)
    t.forward(TL * 10)
    x = t.xcor()
    t.right(angle1)
    t.forward(1000)
    t.back(1500)
    t.forward(500)
    t.left(angle1)
    t.back(TL * 10)
    t.right(angle1)
    t.left(90)
    t.goto(-400, 0)
    t.back(e * 10)
    t.right(90)
    # Drawing of TV
    t.forward(TV * 10)
    t.back(TV * 10)
    t.right(angle2)
    print(angle2)
    t.forward(TL * 10)
    t.left(angle2)
    t.forward(1000)
    t.back(1500)
    t.forward(500)
    x1 = t.xcor()
    y1 = t.xcor()
    t.right(angle2)
    t.back(TL * 10)
    t.left(angle2)
    t.penup()
    t.goto(x, 0)
    t.right(90)
    t.forward(e * 10)
    t.pendown()
    t.right(180)
    t.circle(TV * 10)
    t.penup()
    t.goto(x1, 0)
    t.forward(d * 10)
    t.pendown()
    t.circle(FV * 10)


screen = Screen()
t.screensize(10000, 10000)
t.title("EGL PROJECT")
t.penup()
t.goto(-500, 0)
t.pendown()
t.forward(1000)
t.penup()
t.goto(-400, 0)
t.pendown()
egldrawing()
t.exitonclick()